"""PAD .robin file generator using Jinja2 templates.

Converts an annotated BPProcess into .robin files for Power Automate Desktop flows.
One .robin file per BP page (subsheet).

Main page → {process_name}_main.robin
Sub-pages → {page_name}.robin
"""

from __future__ import annotations

import re
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from flowsmith.ast.models import BPProcess, BPStage, ConfidenceBand
from flowsmith.exceptions import GenerationError


class PADGenerator:
    """Generate .robin files for annotated BP processes."""

    def __init__(self, template_dir: Path | None = None) -> None:
        """Initialise Jinja2 environment from templates/pad/.

        Args:
            template_dir: Override for template directory.
                          Defaults to templates/pad/ relative to project root.

        Raises:
            GenerationError: If template directory not found.
        """
        if template_dir is None:
            template_dir = Path.cwd() / "templates" / "pad"

        if not template_dir.exists():
            raise GenerationError(f"Template directory not found: {template_dir.absolute()}")

        self.template_dir = template_dir
        self.env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            undefined=StrictUndefined,
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate_process(
        self,
        process: BPProcess,
        output_dir: Path,
    ) -> list[Path]:
        """Generate .robin files for an annotated BPProcess.

        One .robin file per BP page (subsheet).
        Main page → {process_name}_main.robin
        Sub-pages → {page_name}.robin

        Args:
            process: Fully annotated BPProcess.
            output_dir: Directory to write .robin files.
                        Created if it does not exist.

        Returns:
            List of Path objects for all generated files.

        Raises:
            GenerationError: If any file cannot be written
                or any template rendering fails.
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        generated_files: list[Path] = []

        try:
            for page in process.pages:
                robin_content = self.generate_page(page, process.name)

                # Sanitise filename
                if page.is_main:
                    filename = f"{self._sanitise_filename(process.name)}_main.robin"
                else:
                    filename = f"{self._sanitise_filename(page.name)}.robin"

                output_path = output_dir / filename
                output_path.write_text(robin_content, encoding="utf-8")
                generated_files.append(output_path)

        except Exception as e:
            raise GenerationError(
                f"Failed to generate .robin files for process '{process.name}': {e}"
            ) from e

        return generated_files

    def generate_page(
        self,
        page,  # BPPage type annotation deferred to avoid circular import
        process_name: str,
    ) -> str:
        """Generate Robin script content for one BP page.

        Args:
            page: The BPPage to generate.
            process_name: Name of the parent process
                          (used in header comments).

        Returns:
            Complete Robin script as a string.

        Raises:
            GenerationError: If any template rendering fails.
        """
        try:
            lines: list[str] = []

            # File header comment
            lines.append("# Generated by Flowsmith")
            lines.append(f"# Process: {process_name}")
            lines.append(f"# Page: {page.name}")
            lines.append(f"# Stages: {len(page.stages)}")
            lines.append("")

            # Flow header (@@ConnectionString etc) — only on main page
            if page.is_main:
                # Collect input variables and sensitive vars from all stages
                input_vars = []
                sensitive_vars = []
                for stage in page.stages:
                    for data_item in stage.data_items:
                        if data_item.is_input:
                            input_vars.append(
                                {
                                    "name": data_item.name,
                                    "data_type": self._map_bp_type_to_robin(data_item.data_type),
                                    "is_optional": False,
                                }
                            )
                            if "pass" in data_item.name.lower() or "key" in data_item.name.lower():
                                sensitive_vars.append(data_item.name)

                header_template = self.env.get_template("flow_header.robin.j2")
                header = header_template.render(
                    inputs=input_vars,
                    sensitive_vars=sensitive_vars,
                )
                lines.append(header)

            # Render one FUNCTION block per page
            action_lines: list[str] = []
            for stage in page.stages:
                rendered = self._render_stage(stage)
                if rendered:
                    action_lines.append(rendered)

            actions_content = "\n".join(action_lines)
            subflow_template = self.env.get_template("subflow.robin.j2")
            subflow = subflow_template.render(
                subflow_name=self._sanitise_filename(page.name),
                actions=actions_content,
            )
            lines.append(subflow)

            return "\n".join(lines)

        except Exception as e:
            raise GenerationError(f"Failed to generate Robin for page '{page.name}': {e}") from e

    def _render_stage(self, stage: BPStage) -> str:
        """Render a single stage to Robin action line(s).

        Dispatches on pa_annotation.band and target_type.
        Never reads stage_type directly.

        Args:
            stage: An annotated BPStage.

        Returns:
            One or more Robin lines as a string.

        Raises:
            GenerationError: If pa_annotation is None.
        """
        if stage.pa_annotation is None:
            raise GenerationError(
                f"Stage '{stage.name}' (ID: {stage.stage_id}) has no pa_annotation. "
                "The annotator must have run before code generation."
            )

        annotation = stage.pa_annotation
        band = annotation.band
        target_type = annotation.target_type
        target_module = annotation.target_module

        # MANUAL band: always render stub
        if band == ConfidenceBand.MANUAL:
            flags = annotation.flags
            reason = flags[0].reason if flags else "No mapping found"
            suggested_fix = flags[0].suggested_fix if flags else "Review manually"
            stub_template = self.env.get_template("actions/stub.robin.j2")
            return stub_template.render(
                stage_id=stage.stage_id,
                stage_name=stage.name,
                reason=reason,
                suggested_fix=suggested_fix,
            )

        # Dispatch on target_type
        lines: list[str] = []

        if target_type == "SetVariable":
            set_template = self.env.get_template("actions/set_variable.robin.j2")
            verify_comment = (
                f"{stage.name} (confidence {annotation.confidence:.2f})"
                if band == ConfidenceBand.SPOT_CHECK
                else None
            )
            rendered = set_template.render(
                var_name=stage.name,
                value="%SomeVar%",  # Placeholder
                verify_comment=verify_comment,
            )
            lines.append(rendered)

        elif target_type == "CreateNewDataTable":
            set_template = self.env.get_template("actions/set_variable.robin.j2")
            rendered = set_template.render(
                var_name=stage.name,
                value="DataTable.Create()",
                verify_comment=None,
            )
            lines.append(rendered)

        elif target_type in ("RunDesktopFlow", "SubFlow"):
            call_template = self.env.get_template("actions/call_subflow.robin.j2")
            rendered = call_template.render(
                subflow_name=stage.name,
            )
            lines.append(rendered)

        elif target_type == "Condition":
            cond_template = self.env.get_template("actions/condition.robin.j2")
            rendered = cond_template.render(
                condition="%SomeVar% = True",  # Placeholder
                band=band.value,
            )
            lines.append(rendered)

        elif target_type == "RunPowershellScript":
            # Always MANUAL for PowerShell
            stub_template = self.env.get_template("actions/stub.robin.j2")
            rendered = stub_template.render(
                stage_id=stage.stage_id,
                stage_name=stage.name,
                reason="PowerShell scripts require manual migration",
                suggested_fix="Convert to inline C# or external script",
            )
            lines.append(rendered)

        elif target_module == "Excel" and band != ConfidenceBand.MANUAL:
            excel_template = self.env.get_template("actions/excel_read.robin.j2")
            rendered = excel_template.render(
                filepath="$'''C:\\path\\to\\file.xlsx'''",
                excel_var="ExcelInstance",
                sheet_name="Sheet1",
                output_var="DataTable",
            )
            lines.append(rendered)

        else:
            # Generic comment for unhandled types
            comment = f"# {target_module}.{target_type}"
            if band == ConfidenceBand.SPOT_CHECK:
                comment += f" # VERIFY: {stage.name} (confidence {annotation.confidence:.2f})"
            elif band == ConfidenceBand.PARTIAL:
                comment += f" # TODO: complete {stage.name}"
            lines.append(comment)

        return "\n".join(lines) if lines else ""

    @staticmethod
    def _sanitise_filename(name: str) -> str:
        """Sanitise a filename by removing/replacing special characters.

        Args:
            name: The filename to sanitise.

        Returns:
            Sanitised filename (spaces → underscores, special chars removed).
        """
        # Replace spaces with underscores
        name = name.replace(" ", "_")
        # Remove special characters, keep only alphanumeric and underscores
        name = re.sub(r"[^a-zA-Z0-9_]", "", name)
        return name or "flow"

    @staticmethod
    def _map_bp_type_to_robin(bp_type: str) -> str:
        """Map Blue Prism data type to Robin type string.

        Args:
            bp_type: Blue Prism type (e.g., 'text', 'number', 'flag', 'collection').

        Returns:
            Robin type string.
        """
        mapping = {
            "text": "String",
            "number": "Number",
            "flag": "Bool",
            "currency": "Number",
            "date": "DateTime",
            "time": "TimeSpan",
            "collection": "RecordSet",
            "binary": "String",
        }
        return mapping.get(bp_type.lower(), "String")
