"""Build Workflow XML elements with embedded PAD script definitions.

Converts generated .robin files and AST metadata into complete Workflow XML
elements suitable for embedding in customizations.xml. Handles:
  - PAD script source embedding (Definition element)
  - Metadata JSON generation (clientversion, schemaVersion, flags)
  - Input/Output schema extraction from AST data items
  - Dependency tracking (child flows, connectors, modules)
  - Connection reference mapping
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Any

from flowsmith.ast.models import BPPage, BPProcess
from flowsmith.exceptions import GenerationError


class WorkflowBuilder:
    """Builds complete Workflow XML elements with embedded PAD definitions."""

    # Default engine version for generated flows
    CREATED_ENGINE_VERSION = {"Major": 2, "Minor": 43, "Build": 0, "Revision": 0}
    DEFAULT_SCHEMA_VERSION = "2022.07"
    DEFAULT_ROBIN_SCHEMA = "ROBIN_20211012"

    def __init__(self) -> None:
        """Initialise the workflow builder."""
        self.workflows: list[dict[str, Any]] = []

    def build_workflow(
        self,
        page: BPPage,
        process: BPProcess,
        robin_file: Path,
        json_file: Path | None = None,
    ) -> dict[str, Any]:
        """Build a complete Workflow element for a BP page.

        Args:
            page: The BPPage to build from.
            process: The parent BPProcess (for name context).
            robin_file: Path to the generated .robin file containing PAD script.
            json_file: Optional path to Cloud Flow JSON file.

        Returns:
            Dictionary containing workflow XML element data ready for templating.

        Raises:
            GenerationError: If robin_file cannot be read or is empty.
        """
        try:
            # Read the .robin file content
            if not robin_file.exists():
                raise GenerationError(f"Robin file not found: {robin_file}")

            robin_content = robin_file.read_text(encoding="utf-8")
            if not robin_content.strip():
                raise GenerationError(f"Robin file is empty: {robin_file}")

            # Escape the content for XML/JSON embedding
            escaped_definition = self._escape_definition(robin_content)

            # Extract metadata from the AST
            inputs_schema = self._build_inputs_schema(page)
            outputs_schema = self._build_outputs_schema(page)
            dependencies = self._build_dependencies(page)
            connection_refs = self._build_connection_references(page)

            # Build metadata JSON
            metadata = self._build_metadata(page)

            # Generate a GUID for the workflow
            workflow_id = str(uuid.uuid4()).upper()

            # Build the workflow element
            workflow = {
                "workflow_id": workflow_id,
                "name": page.name,
                "json_file_name": json_file.name if json_file else f"{page.name}.json",
                "type": 1,  # Workflow type
                "subprocess": 0,
                "category": 6,  # Desktop flow category
                "mode": 0,
                "scope": 4,
                "on_demand": 0,
                "trigger_on_create": 0,
                "trigger_on_delete": 0,
                "async_autodelete": 0,
                "sync_workflow_log_on_failure": 0,
                "state_code": 1,
                "status_code": 2,
                "run_as": 1,
                "is_transacted": 1,
                "introduced_version": "1.0",
                "is_customizable": 1,
                "business_process_type": 0,
                "ui_flow_type": 2,  # Desktop flow marker
                "is_custom_processing_step_allowed_for_other_publishers": 1,
                "modern_flow_type": 0,
                "metadata": metadata,
                "inputs": inputs_schema,
                "outputs": outputs_schema,
                "dependencies": dependencies,
                "connection_references": connection_refs,
                "definition": escaped_definition,
                "schema_version": self.DEFAULT_SCHEMA_VERSION,
                "claims": self._build_claims(page),
                "primary_entity": "none",
                "localized_name": page.name,
                "localized_description": f"Generated by Flowsmith from {process.name}",
            }

            self.workflows.append(workflow)
            return workflow

        except GenerationError:
            raise
        except Exception as e:
            raise GenerationError(f"Failed to build workflow for page '{page.name}': {e}") from e

    def _escape_definition(self, robin_content: str) -> str:
        """Escape PAD script for embedding in JSON Definition element.

        Args:
            robin_content: Raw PAD script source code.

        Returns:
            Escaped string suitable for JSON string embedding.
        """
        # Convert CRLF and LF to \r\n for XML compatibility
        normalized = robin_content.replace("\r\n", "\n").replace("\r", "\n")
        # Escape for JSON embedding
        escaped = normalized.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\r\\n")
        return f'"{escaped}"'

    def _build_inputs_schema(self, page: BPPage) -> str:
        """Build JSON schema for workflow inputs from page data items.

        Args:
            page: The BPPage to extract inputs from.

        Returns:
            JSON string containing the inputs schema.
        """
        input_items = {}
        required_inputs = []

        for stage in page.stages:
            for data_item in stage.data_items:
                if data_item.is_input and data_item.name not in input_items:
                    input_items[data_item.name] = {
                        "isOptional": False,
                        "default": data_item.initial_value or "",
                        "description": "",
                        "type": self._map_bp_type_to_json_type(data_item.data_type),
                        "title": data_item.name,
                    }
                    required_inputs.append(data_item.name)

        if not input_items:
            return json.dumps({"schema": None}, separators=(",", ":"))

        schema = {
            "schema": {
                "type": "object",
                "required": required_inputs,
                "properties": input_items,
            }
        }
        return json.dumps(schema, separators=(",", ":"))

    def _build_outputs_schema(self, page: BPPage) -> str:
        """Build JSON schema for workflow outputs from page data items.

        Args:
            page: The BPPage to extract outputs from.

        Returns:
            JSON string containing the outputs schema.
        """
        output_items = {}

        for stage in page.stages:
            for data_item in stage.data_items:
                if data_item.is_output and data_item.name not in output_items:
                    output_items[data_item.name] = {
                        "type": self._map_bp_type_to_json_type(data_item.data_type),
                        "description": "",
                    }

        if not output_items:
            return json.dumps({"schema": None}, separators=(",", ":"))

        schema = {
            "schema": {
                "type": "object",
                "properties": output_items,
            }
        }
        return json.dumps(schema, separators=(",", ":"))

    def _build_dependencies(self, page: BPPage) -> str:
        """Build dependency object referencing connectors and modules.

        Args:
            page: The BPPage to extract dependencies from.

        Returns:
            JSON string containing dependencies structure.
        """
        child_flows = []
        required_binaries = []

        # Extract module references from annotations
        modules_seen = set()
        for stage in page.stages:
            if stage.pa_annotation:
                module = stage.pa_annotation.target_module
                if module and module not in modules_seen:
                    modules_seen.add(module)
                    # Each module gets a GUID placeholder
                    required_binaries.append(str(uuid.uuid4()).upper())

        dependencies = {
            "childFlows": child_flows,
            "workQueues": [],
            "environmentVariables": [],
            "requiredBinaries": required_binaries,
        }
        return json.dumps(dependencies, separators=(",", ":"))

    def _build_connection_references(self, page: BPPage) -> str:
        """Build connection references for cloud connectors used by the flow.

        Args:
            page: The BPPage to extract connector references from.

        Returns:
            JSON string containing connection references array.
        """
        connections: list[dict[str, Any]] = []
        return json.dumps(connections, separators=(",", ":"))

    def _build_metadata(self, page: BPPage) -> str:
        """Build metadata JSON object for the workflow.

        Args:
            page: The BPPage being packaged.

        Returns:
            JSON string containing workflow metadata.
        """
        metadata = {
            "clientversion": "2.63.163.25342",
            "isvalid": True,
            "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
            "schemaVersion": self.DEFAULT_ROBIN_SCHEMA,
            "containsActiveConnections": False,
            "containsGptPredictActions": False,
            "containsActiveCopilotActions": False,
            "containsActiveWorkQueuesActions": False,
            "containsActiveLogMessageActions": False,
            "containsActiveRepairWithAIActions": False,
            "containsActiveCredentialsActions": False,
            "multipleRequestsState": 0,
            "scriptType": 0,
            "disableScreenshotCaptureOnError": False,
            "missingUiElementRepairType": None,
            "flowTimeout": None,
            "screenResolution": None,
            "flowLogsVerbosity": None,
            "flowGeneratedBy": "Flowsmith",
        }
        return json.dumps(metadata, separators=(",", ":"))

    def _build_claims(self, page: BPPage) -> list[dict[str, str]]:
        """Build Claims array based on page requirements.

        Args:
            page: The BPPage being packaged.

        Returns:
            List of claim dictionaries.
        """
        claims = []

        # Add default claims for desktop flows
        claims.append({"name": "selfheal"})

        # Add connector-specific claims based on annotations
        for stage in page.stages:
            if stage.pa_annotation:
                module = stage.pa_annotation.target_module
                if module.lower() in ["excel", "file", "web", "database"]:
                    # These modules might require specific claims
                    pass

        return claims

    def _map_bp_type_to_json_type(self, bp_type: str) -> str:
        """Map Blue Prism data type to JSON Schema type.

        Args:
            bp_type: Blue Prism data type string.

        Returns:
            JSON Schema type string.
        """
        bp_type_lower = bp_type.lower()
        if "number" in bp_type_lower or "integer" in bp_type_lower:
            return "number"
        elif "flag" in bp_type_lower or "boolean" in bp_type_lower:
            return "boolean"
        elif "collection" in bp_type_lower or "list" in bp_type_lower:
            return "array"
        else:
            return "object" if "custom" in bp_type_lower else "string"
