"""One-off script: analyse Blue Prism .bprelease / .xml samples.

Outputs:
  - Rich terminal report
  - docs/bp_schema_analysis.md

Run with:
  uv run python scripts/analyse_bp_samples.py
"""

from __future__ import annotations

import hashlib
import sys
from collections import Counter, defaultdict
from pathlib import Path

from lxml import etree
from rich.console import Console
from rich.table import Table

SAMPLES_DIR = Path("samples/blueprism")
DOCS_DIR = Path("docs")
OUTPUT_MD = DOCS_DIR / "bp_schema_analysis.md"

console = Console()


def strip_ns(tag: str) -> str:
    """Strip XML namespace prefix from a tag name.

    Args:
        tag: Raw lxml tag string, possibly with namespace prefix.

    Returns:
        Tag name without namespace prefix.
    """
    return tag.split("}")[-1] if "}" in tag else tag


def file_sha256(path: Path) -> str:
    """Compute SHA-256 digest of a file for deduplication.

    Args:
        path: Path to the file.

    Returns:
        Hex digest string.
    """
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def analyse_file(path: Path) -> dict:
    """Parse one BP XML file and return collected schema data.

    Args:
        path: Path to the .bprelease or .xml file.

    Returns:
        Dict with keys: tags, tag_attrs, type_values, stage_type_counts,
        vbo_names, vbo_actions.
    """
    tree = etree.parse(str(path))
    root = tree.getroot()

    tags: set[str] = set()
    tag_attrs: dict[str, set[str]] = defaultdict(set)
    type_values: set[str] = set()
    stage_type_counts: Counter[str] = Counter()
    vbo_names: set[str] = set()
    # Maps vbo_name -> set of action names called on it
    vbo_actions: dict[str, set[str]] = defaultdict(set)

    for elem in root.iter():
        tag = strip_ns(elem.tag)
        tags.add(tag)

        for attr_name, attr_val in elem.attrib.items():
            clean_attr = strip_ns(attr_name)
            tag_attrs[tag].add(clean_attr)
            if clean_attr == "type":
                type_values.add(attr_val)

        # Stage type tallying
        if tag == "stage":
            stype = elem.get("type", "UNKNOWN")
            stage_type_counts[stype] += 1

        # VBO object name (from <object> tags with name= attribute)
        if tag == "object":
            name = elem.get("name", "").strip()
            if name:
                vbo_names.add(name)

        # VBO action calls: <resource object="VBO Name" action="Method Name"/>
        if tag == "resource":
            obj = elem.get("object", "").strip()
            action = elem.get("action", "").strip()
            if obj and action:
                vbo_names.add(obj)
                vbo_actions[obj].add(action)

    return {
        "tags": tags,
        "tag_attrs": tag_attrs,
        "type_values": type_values,
        "stage_type_counts": stage_type_counts,
        "vbo_names": vbo_names,
        "vbo_actions": vbo_actions,
    }


def merge_results(results: list[dict]) -> dict:
    """Merge per-file analysis dicts into one combined result.

    Args:
        results: List of per-file dicts from analyse_file().

    Returns:
        Single merged dict with combined data across all files.
    """
    merged: dict = {
        "tags": set(),
        "tag_attrs": defaultdict(set),
        "type_values": set(),
        "stage_type_counts": Counter(),
        "vbo_names": set(),
        "vbo_actions": defaultdict(set),
    }
    for r in results:
        merged["tags"] |= r["tags"]
        for tag, attrs in r["tag_attrs"].items():
            merged["tag_attrs"][tag] |= attrs
        merged["type_values"] |= r["type_values"]
        merged["stage_type_counts"] += r["stage_type_counts"]
        merged["vbo_names"] |= r["vbo_names"]
        for vbo, actions in r["vbo_actions"].items():
            merged["vbo_actions"][vbo] |= actions
    return merged


# Stage types found in the XML that map to the 17 canonical CLAUDE.md types
_CANONICAL_STAGE_TYPES = {
    "Start",
    "End",
    "Action",
    "Decision",
    "Calculation",
    "Code",
    "WaitStart",
    "WaitEnd",
    "Navigate",
    "Read",
    "Write",
    "LoopStart",
    "LoopEnd",
    "Exception",
    "Recover",
    "Resume",
    "Block",
    "Collection",
    "Data",
}


def build_md_report(merged: dict, file_paths: list[Path]) -> str:
    """Render the analysis as a Markdown string.

    Args:
        merged: Merged analysis result dict.
        file_paths: List of unique files that were analysed.

    Returns:
        Markdown string ready to write to disk.
    """
    lines: list[str] = []
    lines.append("# Blue Prism XML Schema Analysis\n")
    lines.append("_Generated by `scripts/analyse_bp_samples.py`_\n")

    lines.append("## Files analysed\n")
    for p in sorted(file_paths):
        size_kb = p.stat().st_size // 1024
        lines.append(f"- `{p}` ({size_kb:,} KB)")
    lines.append("")

    # Stage types
    lines.append("## Stage type counts\n")
    lines.append("| Stage type | Count | Canonical? |")
    lines.append("| ---------- | ----- | ---------- |")
    for stype, count in sorted(merged["stage_type_counts"].items()):
        canonical = "yes" if stype in _CANONICAL_STAGE_TYPES else "**NO — needs mapping**"
        lines.append(f"| `{stype}` | {count:,} | {canonical} |")
    lines.append("")

    # VBO names and their methods
    lines.append("## VBO / Object names and methods called\n")
    lines.append(f"Total unique VBOs: **{len(merged['vbo_names'])}**\n")
    for name in sorted(merged["vbo_names"]):
        methods = sorted(merged["vbo_actions"].get(name, set()))
        lines.append(f"### `{name}`\n")
        if methods:
            for m in methods:
                lines.append(f"- `{m}`")
        else:
            lines.append("_No method calls recorded (referenced by name only)_")
        lines.append("")

    # All XML tags
    lines.append("## All unique XML tags\n")
    lines.append(f"Total unique tags: **{len(merged['tags'])}**\n")
    lines.append("| Tag | Attributes |")
    lines.append("| --- | ---------- |")
    for tag in sorted(merged["tags"]):
        attrs = sorted(merged["tag_attrs"].get(tag, set()))
        attr_str = ", ".join(f"`{a}`" for a in attrs) if attrs else "—"
        lines.append(f"| `{tag}` | {attr_str} |")
    lines.append("")

    # Type attribute values
    lines.append("## All unique `type` attribute values\n")
    for v in sorted(merged["type_values"]):
        lines.append(f"- `{v}`")
    lines.append("")

    # Non-canonical stage types
    lines.append("## Non-canonical stage types (require manual mapping)\n")
    non_canonical = sorted(
        t for t in merged["stage_type_counts"] if t not in _CANONICAL_STAGE_TYPES
    )
    if non_canonical:
        lines.append(
            "These stage types appear in the XML but are NOT in the 14 canonical "
            "types defined in CLAUDE.md. Each needs an explicit parser + mapping decision.\n"
        )
        lines.append("| Stage type | Count | Suggested handling |")
        lines.append("| ---------- | ----- | ------------------ |")
        suggestions = {
            "Anchor": "Skip — routing connector only, no logic",
            "Block": "Emit as PAD BLOCK...ON BLOCK ERROR scope boundary (not a throw)",
            "Collection": "Emit as PAD DataTable variable declaration (preserves column schema)",
            "MultipleCalculation": "Treat as multiple CALCULATION stages",
            "Note": "Skip — comment annotation only",
            "Process": "Metadata — skip or emit as process header",
            "ProcessInfo": "Metadata — skip",
            "SubSheet": "Map to sub-flow call (CALL stage)",
            "SubSheetInfo": "Metadata — skip",
        }
        for t in non_canonical:
            count = merged["stage_type_counts"][t]
            suggestion = suggestions.get(t, "Unknown — review manually")
            lines.append(f"| `{t}` | {count:,} | {suggestion} |")
    else:
        lines.append("_None — all stage types map to canonical types._")
    lines.append("")

    return "\n".join(lines)


def print_rich_report(merged: dict, file_paths: list[Path]) -> None:
    """Print a structured Rich terminal report.

    Args:
        merged: Merged analysis result dict.
        file_paths: List of unique files that were analysed.
    """
    console.rule("[bold cyan]Blue Prism XML Schema Analysis[/bold cyan]")

    console.print(f"\n[bold]Files analysed:[/bold] {len(file_paths)}")
    for p in sorted(file_paths):
        size_kb = p.stat().st_size // 1024
        console.print(f"  [dim]{p}[/dim] ({size_kb:,} KB)")

    # Stage types table
    console.print()
    t = Table(title="Stage Type Counts", show_header=True, header_style="bold magenta")
    t.add_column("Stage Type", style="cyan")
    t.add_column("Count", justify="right")
    t.add_column("Canonical?")
    for stype, count in sorted(merged["stage_type_counts"].items()):
        is_canonical = stype in _CANONICAL_STAGE_TYPES
        canonical_str = "[green]yes[/green]" if is_canonical else "[red]NO[/red]"
        t.add_row(stype, f"{count:,}", canonical_str)
    console.print(t)

    # VBO table
    console.print()
    total_methods = sum(len(v) for v in merged["vbo_actions"].values())
    t2 = Table(
        title=f"VBOs ({len(merged['vbo_names'])} unique, {total_methods} unique method calls)",
        show_header=True,
        header_style="bold magenta",
    )
    t2.add_column("VBO Name", style="green")
    t2.add_column("Methods called", justify="right")
    for name in sorted(merged["vbo_names"]):
        methods = merged["vbo_actions"].get(name, set())
        t2.add_row(name, str(len(methods)))
    console.print(t2)

    # Non-canonical
    non_canonical = sorted(
        t for t in merged["stage_type_counts"] if t not in _CANONICAL_STAGE_TYPES
    )
    if non_canonical:
        console.print()
        console.print("[bold red]Stage types with NO canonical PAD mapping:[/bold red]")
        for nc in non_canonical:
            count = merged["stage_type_counts"][nc]
            console.print(f"  [red]!![/red] {nc} ({count:,} occurrences)")

    console.print(f"\n[bold]Total unique XML tags:[/bold] {len(merged['tags'])}")
    console.print(f"[bold]Total unique type-attribute values:[/bold] {len(merged['type_values'])}")


def main() -> None:
    """Entry point: run analysis, print report, save Markdown."""
    all_paths = [
        p for p in SAMPLES_DIR.rglob("*") if p.is_file() and p.suffix in {".bprelease", ".xml"}
    ]

    if not all_paths:
        console.print(f"[red]No .bprelease or .xml files found in {SAMPLES_DIR}[/red]")
        sys.exit(1)

    # Deduplicate files by content hash (e.g. .xml and .bprelease may be identical)
    seen_hashes: set[str] = set()
    file_paths: list[Path] = []
    for p in sorted(all_paths):
        digest = file_sha256(p)
        if digest not in seen_hashes:
            seen_hashes.add(digest)
            file_paths.append(p)

    skipped = len(all_paths) - len(file_paths)
    console.print(
        f"[dim]Found {len(all_paths)} file(s) in {SAMPLES_DIR}, "
        f"{skipped} duplicate(s) removed, analysing {len(file_paths)}...[/dim]"
    )

    results = [analyse_file(p) for p in file_paths]
    merged = merge_results(results)

    print_rich_report(merged, file_paths)

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    md = build_md_report(merged, file_paths)
    OUTPUT_MD.write_text(md, encoding="utf-8")
    console.print(f"\n[green]OK[/green] Markdown report saved -> [bold]{OUTPUT_MD}[/bold]")


if __name__ == "__main__":
    main()
